export const recentBranches = [
  {
    id: 1,
    name: "Keystone Bank",
    address: "50,Isaac street Somolu",
    city: "Lagos",
    manager: "Wade Warren",
    operationManager: "John Doe",
  },
  {
    id: 2,
    name: "Keystone Bank",
    address: "50,Isaac street Somolu",
    city: "Lagos",
    manager: "Wade Warren",
    operationManager: "John Doe",
  },
  {
    id: 3,
    name: "Keystone Bank",
    address: "50,Isaac street Somolu",
    city: "Lagos",
    manager: "Wade Warren",
    operationManager: "John Doe",
  },
  {
    id: 4,
    name: "Keystone Bank",
    address: "50,Isaac street Somolu",
    city: "Lagos",
    manager: "Wade Warren",
    operationManager: "John Doe",
  },
  {
    id: 5,
    name: "Keystone Bank",
    address: "50,Isaac street Somolu",
    city: "Lagos",
    manager: "Wade Warren",
    operationManager: "John Doe",
  },
  {
    id: 6,
    name: "Keystone Bank",
    address: "50,Isaac street Somolu",
    city: "Lagos",
    manager: "Wade Warren",
    operationManager: "John Doe",
  },
];
