export const listAccountsData = [
  {
    id: 1,
    number: "2012001233",
    balance: "NGN 20,000",
    type: "Savings",
    customer: "Blessed Okonette Okon",
    branch: "Ilupeju",
    manager: "Philip Mathew",
  },
  {
    id: 2,
    number: "2012001233",
    balance: "NGN 20,000",
    type: "Savings",
    customer: "Blessed Okonette Okon",
    branch: "Ilupeju",
    manager: "Philip Mathew",
  },
  {
    id: 3,
    number: "2012001233",
    balance: "NGN 20,000",
    type: "Savings",
    customer: "Blessed Okonette Okon",
    branch: "Ilupeju",
    manager: "Philip Mathew",
  },
  {
    id: 4,
    number: "2012001233",
    balance: "NGN 20,000",
    type: "Savings",
    customer: "Blessed Okonette Okon",
    branch: "Ilupeju",
    manager: "Philip Mathew",
  },
  {
    id: 5,
    number: "2012001233",
    balance: "NGN 20,000",
    type: "Savings",
    customer: "Blessed Okonette Okon",
    branch: "Ilupeju",
    manager: "Philip Mathew",
  },
  {
    id: 6,
    number: "2012001233",
    balance: "NGN 20,000",
    type: "Savings",
    customer: "Blessed Okonette Okon",
    branch: "Ilupeju",
    manager: "Philip Mathew",
  },
  {
    id: 7,
    number: "2012001233",
    balance: "NGN 20,000",
    type: "Savings",
    customer: "Blessed Okonette Okon",
    branch: "Ilupeju",
    manager: "Philip Mathew",
  },
  {
    id: 8,
    number: "2012001233",
    balance: "NGN 20,000",
    type: "Savings",
    customer: "Blessed Okonette Okon",
    branch: "Ilupeju",
    manager: "Philip Mathew",
  },
];
