export const corporateTableData = [
  {
    id: 1,
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    phone: "09087654321",
    bizName: "Cross PLC",
  },
  {
    id: 2,
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    phone: "09087654321",
    bizName: "Cross PLC",
  },
  {
    id: 3,
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    phone: "09087654321",
    bizName: "Cross PLC",
  },
  {
    id: 4,
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    phone: "09087654321",
    bizName: "Cross PLC",
  },
  {
    id: 5,
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    phone: "09087654321",
    bizName: "Cross PLC",
  },
  {
    id: 6,
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    phone: "09087654321",
    bizName: "Cross PLC",
  },
  {
    id: 7,
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    phone: "09087654321",
    bizName: "Cross PLC",
  },
  {
    id: 8,
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    phone: "09087654321",
    bizName: "Cross PLC",
  },
];
