export const individualTableData = [
  {
    id: 1,
    customerType: "IC",
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    bizName: "NIL",
  },
  {
    id: 2,
    customerType: "IC",
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    bizName: "NIL",
  },
  {
    id: 3,
    customerType: "IC",
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    bizName: "NIL",
  },
  {
    id: 4,
    customerType: "IC",
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    bizName: "NIL",
  },
  {
    id: 5,
    customerType: "IC",
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    bizName: "NIL",
  },
  {
    id: 6,
    customerType: "IC",
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    bizName: "NIL",
  },
  {
    id: 7,
    customerType: "IC",
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    bizName: "NIL",
  },
  {
    id: 8,
    customerType: "IC",
    title: "Mr",
    firstName: "Blessed",
    middleName: "Okenette",
    lastName: "Okon",
    bizName: "NIL",
  },
];
